# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170216_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='decription',
            new_name='description',
        ),
    ]
